version: '2'

services:

  app:
    build:
      context: ./
      dockerfile: _docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  # web server container
  web:
    build:
      context: ./
      dockerfile: _docker/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    volumes:
      - ./:/var/www
    links:
      - app
    ports:
      - 80:80
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
